app:
  name: "Client Management System"
  version: "1.0.0"
  host: "127.0.0.1"
  port: 8000

database:
  url: "sqlite:////Users/arhtur/Bases de datos/lineaBase"
  url-postgresql:  "postgresql://postgres:1234@localhost:5433/postgres"
  schema: "public"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

sqs:
  url-queue-client: "https://sqs.us-east-1.amazonaws.com/142911054234/client-queue"
  queue-client-name: "client-queue"

url-queue-client: "https://sqs.us-east-1.amazonaws.com/142911054234/client-queue"

